-- MySQL Script generated by MySQL Workbench
-- Fri Jul 25 15:54:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cnp_connect
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cnp_connect
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cnp_connect` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema CNP_CONNECT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CNP_CONNECT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CNP_CONNECT` DEFAULT CHARACTER SET utf8 ;
USE `cnp_connect` ;

-- -----------------------------------------------------
-- Table `cnp_connect`.`line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`line` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`train` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `line_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Train_Line_idx` (`line_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_Train_Line`
    FOREIGN KEY (`line_id`)
    REFERENCES `cnp_connect`.`line` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `hiring_at` DATE NOT NULL,
  `is_connected` TINYINT NOT NULL DEFAULT 0,
  `is_available` TINYINT NOT NULL DEFAULT 0,
  `is_actif` TINYINT NOT NULL DEFAULT 1,
  `avatar_url` VARCHAR(200) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  UNIQUE INDEX `avatar_url_UNIQUE` (`avatar_url` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `cnp_connect`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`alert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`alert` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `priority` ENUM('soft', 'medium', 'urgent') NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_alert_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_alert_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cnp_connect`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`line_alert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`line_alert` (
  `line_id` INT UNSIGNED NOT NULL,
  `alert_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`line_id`, `alert_id`),
  INDEX `fk_Line_has_Alert_Alert1_idx` (`alert_id` ASC) VISIBLE,
  INDEX `fk_Line_has_Alert_Line1_idx` (`line_id` ASC) VISIBLE,
  CONSTRAINT `fk_Line_has_Alert_Line1`
    FOREIGN KEY (`line_id`)
    REFERENCES `cnp_connect`.`line` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Line_has_Alert_Alert1`
    FOREIGN KEY (`alert_id`)
    REFERENCES `cnp_connect`.`alert` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`capacity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`capacity` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`role_capacity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`role_capacity` (
  `capacity_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`capacity_id`, `role_id`),
  INDEX `fk_Capacity_has_Role_Role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_Capacity_has_Role_Capacity1_idx` (`capacity_id` ASC) VISIBLE,
  CONSTRAINT `fk_Capacity_has_Role_Capacity1`
    FOREIGN KEY (`capacity_id`)
    REFERENCES `cnp_connect`.`capacity` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Capacity_has_Role_Role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `cnp_connect`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`assigned_train`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`assigned_train` (
  `train_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`train_id`, `user_id`),
  INDEX `fk_Train_has_User_User1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Train_has_User_Train1_idx` (`train_id` ASC) VISIBLE,
  CONSTRAINT `fk_Train_has_User_Train1`
    FOREIGN KEY (`train_id`)
    REFERENCES `cnp_connect`.`train` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Train_has_User_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cnp_connect`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`conversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`conversation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC) INVISIBLE,
  INDEX `fk_conversation_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_conversation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cnp_connect`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `file_url` VARCHAR(100) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `conversation_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MESSAGE_conversation1_idx` (`conversation_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_message_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_MESSAGE_conversation1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `cnp_connect`.`conversation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cnp_connect`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`participate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`participate` (
  `User_id` INT UNSIGNED NOT NULL,
  `conversation_id` INT UNSIGNED NOT NULL,
  `is_hide` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`User_id`, `conversation_id`),
  INDEX `fk_User_has_conversation_conversation1_idx` (`conversation_id` ASC) VISIBLE,
  INDEX `fk_User_has_conversation_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_conversation_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `cnp_connect`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_conversation_conversation1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `cnp_connect`.`conversation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`readed_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`readed_message` (
  `user_id` INT UNSIGNED NOT NULL,
  `message_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`message_id`, `user_id`),
  INDEX `fk_user_has_message_message1_idx` (`message_id` ASC) VISIBLE,
  INDEX `fk_user_has_message_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_message_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cnp_connect`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_message_message1`
    FOREIGN KEY (`message_id`)
    REFERENCES `cnp_connect`.`message` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`readed_alert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`readed_alert` (
  `user_id` INT UNSIGNED NOT NULL,
  `alert_id` INT UNSIGNED NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `alert_id`),
  INDEX `fk_user_has_alert_alert1_idx` (`alert_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_alert_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cnp_connect`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_alert_alert1`
    FOREIGN KEY (`alert_id`)
    REFERENCES `cnp_connect`.`alert` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cnp_connect`.`assigned_line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cnp_connect`.`assigned_line` (
  `line_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`line_id`, `user_id`),
  INDEX `fk_line_has_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_line_has_user_line1_idx` (`line_id` ASC) VISIBLE,
  CONSTRAINT `fk_line_has_user_line1`
    FOREIGN KEY (`line_id`)
    REFERENCES `cnp_connect`.`line` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_line_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cnp_connect`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `CNP_CONNECT` ;

-- -----------------------------------------------------
-- Table `CNP_CONNECT`.`CONVERSATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CNP_CONNECT`.`CONVERSATION` (
  `ID` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `CREATED-AT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` INT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USER_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CNP_CONNECT`.`MESSAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CNP_CONNECT`.`MESSAGE` (
  `ID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `CONTENT` TEXT NOT NULL,
  `FILE_URL` VARCHAR(100) NULL DEFAULT NULL,
  `CREATED_AT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USER_ID` INT UNSIGNED NOT NULL,
  `CONVERSATION_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `CONVERSATION_ID`),
  INDEX `fk_MESSAGE_CONVERSATION_idx` (`CONVERSATION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_MESSAGE_CONVERSATION`
    FOREIGN KEY (`CONVERSATION_ID`)
    REFERENCES `CNP_CONNECT`.`CONVERSATION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CNP_CONNECT`.`travel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CNP_CONNECT`.`travel` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `station_one` VARCHAR(100) NOT NULL,
  `station_two` VARCHAR(100) NOT NULL,
  `duration` INT UNSIGNED NOT NULL,
  `line_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_travel_line1_idx` (`line_id` ASC) VISIBLE,
  UNIQUE INDEX `line_id_UNIQUE` (`line_id` ASC) VISIBLE,
  CONSTRAINT `fk_travel_line1`
    FOREIGN KEY (`line_id`)
    REFERENCES `cnp_connect`.`line` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CNP_CONNECT`.`train_travel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CNP_CONNECT`.`train_travel` (
  `travel_id` INT UNSIGNED NOT NULL,
  `train_id` INT UNSIGNED NOT NULL,
  `start_time` DATETIME NULL,
  INDEX `fk_travel_has_train_train1_idx` (`train_id` ASC) VISIBLE,
  INDEX `fk_travel_has_train_travel1_idx` (`travel_id` ASC) VISIBLE,
  PRIMARY KEY (`travel_id`, `train_id`),
  CONSTRAINT `fk_travel_has_train_travel1`
    FOREIGN KEY (`travel_id`)
    REFERENCES `CNP_CONNECT`.`travel` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_travel_has_train_train1`
    FOREIGN KEY (`train_id`)
    REFERENCES `cnp_connect`.`train` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
